### PR TITLE
Add support for multiple E3DC units 

### LINKED ISSUE #123: Support for multiple wallboxes
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm not sure if this should be a bug report or an enhancement. 

Configuring 1 wallbox in HA works great. But as soon as I configure the second, the data gets merged. The graphs look identical with a bunch of spikes. So I assume multiple wallboxes are not supported.

**data when 1 Wallbox is configured:**
Scherm­afbeelding 2024-03-19 om 11 50 09

**data when 2 Wallboxes are configured:**
Scherm­afbeelding 2024-03-19 om 11 50 15

My hardware is 2x S10E_Pro

### Describe the solution you'd like

Support for multiple wallboxes

### Describe alternatives you've considered

Running with only 1 wallbox configured

### Additional context

_No response_

### Diagnostics dump

_No response_

### PR DESCRIPTION
**Pull request by thijsdewitt**
Fix data fetching when you have multiple e3dc units configured

Fixes #123

### CODE REVIEW

**Comment by torbennehmer** [comment]
I think the problem is something else, the data store is static, not instance-specific. Let me check this these days, I'll get back to you as soon as I can. The statics need to move to instance variables, that should solve that part.

**Comment by thijsdewitt** [comment]
Looks like you're right. Changing it to instance variables fixes the problem for me.

**Comment by torbennehmer** [comment]
@thijsdewitt Thanks very much for fixing and testing this!

**Comment by torbennehmer** [comment]
@thijsdewitt Release https://github.com/torbennehmer/hacs-e3dc/releases/tag/v3.7.0-beta.1 includes your change, could you please validate this from your end?

**Comment by thijsdewitt** [comment]
Everything looks to be working properly

**Pull request merged**
